apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-cctq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-cctq
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-cctq
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-cctq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-cctq
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-jeol-tenant/appstudio/dc-metro-map-cctq@sha256:a1929f58c98de8b12c704bf675a66fc95bbb38c4b6dc8b17fe63a138ba06be83
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
